services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
  seed:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./seed:/seed:ro
    command: >
      bash -lc "
      mongoimport --uri mongodb://mongo:27017/realestate --collection owners --file /seed/owners.json --jsonArray &&
      mongoimport --uri mongodb://mongo:27017/realestate --collection properties --file /seed/properties.json --jsonArray &&
      mongoimport --uri mongodb://mongo:27017/realestate --collection propertyImages --file /seed/propertyImages.json --jsonArray &&
      mongoimport --uri mongodb://mongo:27017/realestate --collection propertyTraces --file /seed/propertyTraces.json --jsonArray
      "
volumes:
  mongo_data:
